"""empty message

Revision ID: 376fb8dab255
Revises: 
Create Date: 2025-04-10 09:42:07.214393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '376fb8dab255'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS users')
    op.execute('CREATE SCHEMA IF NOT EXISTS tasks')
    
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор пользователя'),
        sa.Column('username', sa.String(), nullable=False, comment='Логин пользователя'),
        sa.Column('password', sa.String(), nullable=False, comment='Пароль пользователя'),
        sa.Column('email', sa.String(), nullable=False, comment='Email пользователя'),
        sa.Column('first_name', sa.String(), nullable=False, comment='Имя пользователя'),
        sa.Column('last_name', sa.String(), nullable=False, comment='Фамилия пользователя'),
        sa.Column('created_at', sa.Date(), nullable=False, comment='Дата создания пользователя'),
        sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False, comment='Флаг суперпользователя'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username'),
        schema='users',
        comment='Таблица для хранения пользователей'
    )
    op.create_table('boards',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор доски'),
        sa.Column('name', sa.String(), nullable=False, comment='Название доски'),
        sa.Column('owner_id', sa.Integer(), nullable=False, comment='Идентификатор владельца доски'),
        sa.ForeignKeyConstraint(['owner_id'], ['users.users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='tasks',
        comment='Таблица для хранения досок'
    )
    op.create_table('stacks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор стопки'),
        sa.Column('name', sa.String(), nullable=False, comment='Название стопки'),
        sa.Column('board_id', sa.Integer(), nullable=False, comment='Идентификатор доски'),
        sa.ForeignKeyConstraint(['board_id'], ['tasks.boards.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='tasks',
        comment='Таблица для хранения стопок задач'
    )
    op.create_table('priorities',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор приоритета'),
        sa.Column('name', sa.String(), nullable=False, comment='Название приоритета'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        schema='tasks',
        comment='Таблица для хранения приоритетов задач'
    )
    op.create_table('tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор метки'),
        sa.Column('name', sa.String(), nullable=False, comment='Название метки'),
        sa.Column('board_id', sa.Integer(), nullable=False, comment='Идентификатор доски'),
        sa.ForeignKeyConstraint(['board_id'], ['tasks.boards.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        schema='tasks',
        comment='Таблица для хранения меток задач'
    )
    op.create_table('tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор задачи'),
        sa.Column('stack_id', sa.Integer(), nullable=False, comment='Идентификатор стопки'),
        sa.Column('title', sa.String(), nullable=False, comment='Название задачи'),
        sa.Column('create_date', sa.DateTime(), nullable=False, comment='Дата создания задачи'),
        sa.Column('date_end', sa.DateTime(), nullable=True, comment='Дата завершения задачи'),
        sa.Column('priority_id', sa.Integer(), nullable=False, comment='Идентификатор приоритета задачи'),
        sa.Column('description', sa.String(), nullable=True, comment='Описание задачи'),
        sa.Column('solution', sa.String(), nullable=True, comment='Решение задачи'),
        sa.Column('archived', sa.Boolean(), nullable=False, comment='Флаг архивирования задачи'),
        sa.ForeignKeyConstraint(['priority_id'], ['tasks.priorities.id'], ),
        sa.ForeignKeyConstraint(['stack_id'], ['tasks.stacks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema='tasks',
        comment='Таблица для хранения задач'
    )
    op.create_table('task_tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор связи'),
        sa.Column('task_id', sa.Integer(), nullable=False, comment='Идентификатор задачи'),
        sa.Column('tag_id', sa.Integer(), nullable=False, comment='Идентификатор метки'),
        sa.ForeignKeyConstraint(['tag_id'], ['tasks.tags.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['task_id'], ['tasks.tasks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_id', 'tag_id', name='uq_task_tags'),
        schema='tasks',
        comment='Таблица для связи задач и меток'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users', schema='users')
    op.drop_table('boards', schema='tasks')
    op.drop_table('stacks', schema='tasks')
    op.drop_table('priorities', schema='tasks')
    op.drop_table('tags', schema='tasks')
    op.drop_table('tasks', schema='tasks')
    op.drop_table('task_tags', schema='tasks')
    
    op.execute('DROP SCHEMA IF EXISTS tasks')
    op.execute('DROP SCHEMA IF EXISTS users')
    # ### end Alembic commands ###
