"""Add tables tasks

Revision ID: 39e4548c3968
Revises: e7f28840204a
Create Date: 2025-02-27 11:21:12.784805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e4548c3968'
down_revision: Union[str, None] = 'e7f28840204a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS tasks')
    op.create_table('labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tasks',
    comment='Таблица для хранения меток задач'
    )
    op.create_table('priorities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tasks',
    comment='Таблица для хранения приоритетов задач'
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tasks',
    comment='Таблица для хранения статусов задач'
    )
    op.create_table('spaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks',
    comment='Таблица для хранения пространств'
    )
    op.create_table('space_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['tasks.spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'user_id', name='uq_space_user'),
    schema='tasks',
    comment='Таблица для связи пространств и пользователей'
    )
    op.create_table('stacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['tasks.spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks',
    comment='Таблица для хранения колонок'
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stack_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['priority_id'], ['tasks.priorities.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['tasks.stacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['tasks.statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks',
    comment='Таблица для хранения задач'
    )
    op.create_table('task_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['tasks.labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_id', 'task_id', name='uq_task_labels'),
    schema='tasks',
    comment='Таблица для связи пространств и пользователей'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_labels', schema='tasks')
    op.drop_table('tasks', schema='tasks')
    op.drop_table('stacks', schema='tasks')
    op.drop_table('space_users', schema='tasks')
    op.drop_table('spaces', schema='tasks')
    op.drop_table('users', schema='users')
    op.drop_table('statuses', schema='tasks')
    op.drop_table('priorities', schema='tasks')
    op.drop_table('labels', schema='tasks')
    # ### end Alembic commands ###
