"""Init database

Revision ID: 6e76a848013f
Revises: 
Create Date: 2025-02-16 21:25:28.075622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e76a848013f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create schemas
    op.execute('CREATE SCHEMA IF NOT EXISTS users')
    op.execute('CREATE SCHEMA IF NOT EXISTS tasks')
    op.execute('CREATE SCHEMA IF NOT EXISTS docs')
    
    # Create tables
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    schema='users',
    comment='Таблица для хранения пользователей'
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tasks',
    comment='Таблица для хранения меток задач'
    )
    op.create_table('priorities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tasks',
    comment='Таблица для хранения приоритетов задач'
    )
    op.create_table('spaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks',
    comment='Таблица для хранения пространств'
    )
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='tasks',
    comment='Таблица для хранения статусов задач'
    )
    op.create_table('columns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['tasks.spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks',
    comment='Таблица для хранения колонок'
    )
    op.create_table('space_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['tasks.spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks',
    comment='Таблица для связи пространств и пользователей'
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('column_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['column_id'], ['tasks.columns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_id'], ['tasks.priorities.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['tasks.statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks',
    comment='Таблица для хранения задач'
    )
    op.create_table('tasks_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['tasks.labels.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tasks',
    comment='Таблица для связи задач и меток'
    )
    op.create_table('spaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='docs',
    comment='Таблица для хранения пространств'
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['docs.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['docs.spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='docs',
    comment='Таблица для хранения документов'
    )
    op.create_table('space_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['docs.spaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='docs',
    comment='Таблица для связи пространств и пользователей'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('space_user', schema='docs')
    op.drop_table('documents', schema='docs')
    op.drop_table('spaces', schema='docs')
    op.drop_table('tasks_labels', schema='tasks')
    op.drop_table('tasks', schema='tasks')
    op.drop_table('space_user', schema='tasks')
    op.drop_table('columns', schema='tasks')
    op.drop_table('statuses', schema='tasks')
    op.drop_table('spaces', schema='tasks')
    op.drop_table('priorities', schema='tasks')
    op.drop_table('labels', schema='tasks')
    op.drop_table('users', schema='users')
    
    # Drop schemas
    op.execute('DROP SCHEMA IF EXISTS docs CASCADE')
    op.execute('DROP SCHEMA IF EXISTS tasks CASCADE')
    op.execute('DROP SCHEMA IF EXISTS users CASCADE')
    # ### end Alembic commands ###
